gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc@12
  mpi:
      spec: cray-mpich@8.1.29
      gpu: cuda
  unify: true
  specs:
  - py-tensorflow
  - aws-ofi-nccl
  variants:
  - cuda_arch=90
  views:
    default:
