gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc@12
  mpi:
      spec: cray-mpich@8.1.28
      gpu: cuda
  unify: true
  specs:
  - q-e-sirius@develop-ristretto
  - sirius @develop %gcc +apps +cuda
  variants:
  - cuda_arch=90
  views:
    default:
