gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc@12
      - toolchain: llvm
        spec: nvhpc
  mpi:
      spec: cray-mpich@8.1.29
      gpu: cuda
  unify: true
  specs:
  - nvhpc
  - osu-micro-benchmarks+cuda%nvhpc
  - cray-mpich%nvhpc
  - cuda
  - libxml2%gcc
  - cmake%gcc
  variants:
  - cuda_arch=90
  views:
    default:
