gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc@12
      - toolchain: llvm
        spec: nvhpc
  mpi:
      spec: cray-mpich@8.1.28
      gpu: cuda
  unify: true
  specs:
  - osu-micro-benchmarks+cuda %nvhpc
  - libxml2%gcc
  - python%gcc
  - cmake%gcc
  variants:
  - cuda_arch=90
  views:
    default:
