gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc@12
  mpi:
      spec: cray-mpich@8.1.28
      gpu: cuda
  unify: true
  specs:
  - osu-micro-benchmarks+cuda %gcc
  - cmake
  - python
  - openblas%gcc
  variants:
  - cuda_arch=90
  views:
    default:
